name: Cache example workflow

on:
  push:
    paths:
      - '.github/workflows/Caching_example.yml'

jobs:
  Build-Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Install Dependencies"
        run: |
          python - pip install --upgrade pip
          pip install pandas openpxl

