name: Practice examples

on:
  push:
  workflow_dispatch:

jobs:
  Multistep-Job:
    runs-on: 'windows-latest'
    steps:
      - name: 'Git Checkout'
        run: echo "This is git checkout stage"

      - name: 'Stage 1 execution'
        run: Start-Sleep -s 10

      - name: 'Upload artifacts'
        run: echo "Artifacts are published to jforg"

      - name: 'Email Notification'
        run: echo "Email to end user"

  Cloned-second-Job:
    runs-on: 'windows-latest'
    steps:
      - name: 'Git Checkout'
        run: echo "This is git checkout stage"

      - name: 'Stage 1 execution'
        run: Start-Sleep -s 10

      - name: 'Upload artifacts'
        run: echo "Artifacts are published to jforg"

      - name: 'Email Notification'
        run: echo "Email to end user"

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        run: echo "This is git checkout stage"

      - name: 'Stage 1 execution'
        run: Start-Sleep -s 10

      - name: 'Upload artifacts'
        run: echo "Artifacts are published to jforg"

      - name: 'Email Notification'
        run: echo "Email to end user"

  Test_A:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        run: echo "This is git checkout stage"

      - name: 'Stage 1 execution'
        run: Start-Sleep -s 10

      - name: 'Upload artifacts'
        run: echo "Artifacts are published to jforg"

      - name: 'Email Notification'
        run: echo "Email to end user"

  Test_B:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        run: echo "This is git checkout stage"

      - name: 'Stage 1 execution'
        run: Start-Sleep -s 10

      - name: 'Upload artifacts'
        run: echo "Artifacts are published to jforg"

      - name: 'Email Notification'
        run: echo "Email to end user"

  Deploy:
    needs: [ Test_A, Test_B ] # List multiple jobs in brackets
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        run: echo "This is git checkout stage"

      - name: 'Stage 1 execution'
        run: Start-Sleep -s 10

      - name: 'Upload artifacts'
        run: echo "Artifacts are published to jforg"

      - name: 'Email Notification'
        run: echo "Email to end user"